apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      version: "5.5.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    rbac:
      serviceAccountName: external-dns
    registry: "txt"
    txtPrefix: "txt."
    policy: sync
    logLevel: info