apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring

  values:
    controller:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true

      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: nginx.josa.kubechamp.gq
          service.beta.kubernetes.io/azure-load-balancer-internal: "false"

      ingressClassResource:
        name: nginx
        enabled: true
        default: false
        controllerValue: "k8s.io/ingress-nginx"