apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-controllers
  namespace: flux-system
  labels:
    prometheusDiscovery: enabled
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchExpressions:
      - key: app
        operator: Exists
        # values:
        #   - helm-controller
        #   - source-controller
        #   - kustomize-controller
        #   - notification-controller
        #   - image-automation-controller
        #   - image-reflector-controller
  podMetricsEndpoints:
    - port: http-prom