apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-credentials
  namespace: external-dns
spec:
  encryptedData:
    external-dns-credentials.yaml: AgAYPyg040AiclFSXnj8NQh9QZANZ2q098EKkAUvameDswOyD/bWw/3RYlPl4ERVI/pPfJjTc9PtsTbVGPgK8U4peq09UET6Wqd0MatkRKkiDvCzpQsePZBj8jSZj5rrEoZdsR5UtkgcWoc2qC26UWza9ZSosIXq3tjDa7u3Zrui+cBiBF/thCP4ZnH8QnfxUg0yjEgne7FgJ29mXYKmB68ylCFwQelbjYWS6D86wrRIU/PIfqmXteXjLSekkCOR1Ks73dnB8NBXNZK/d1XeelRPrnLNqQ6v+41+7rZ+yXLx73Uu0lfhKoYWb26oWO5asn7KA/Lf40qO6bOVUq81Q+6OOtRCeSpl4YfpPh/kCW01gy8ZdF8RMLZkndo2GNFn2KfzqwtL82AfANZf17fxUMGAMgFvUZFYzBeZ2+ZHh989fqm11pOIeVrk4iZQ9+rp1qey9XCNmw/pm+fJf/J3YgaOTQP99hmCkgAGzhxc0g4BXR9ShIVLnD1t0em7vXg7Kdy7d5JEuHzyRZqNoFpI21t+5hWsWLTurvJQ6BCiQKQDRLpWjHviPHwoVUVq+ZOKyhhxUjxMTk2VCwfCYPI2+zrXuTMIjI7Y7jEOZA7NztmJlALveUJ5QIgbiFi44rMHmGXdk3TdWv2ZhuprZlRtukBDXeivuIN3ikM7bV8GizAKiTRqhiX879u7gD6D9TmcDYlhbAzhDNqMD+KMYoWtK+7FT6AlkLEmPIT0db40OQPLp3rpY/P/PnBAtWjzOM6oHlZpNAoSE6CWP9p63VrEkXS7LqWm2WnvJZR+RVbCKwsuYWUJQkISdPB6pXZly1GSK2SQSQVFYkf95Qz1YwB5tNF11SBci4eW2AVLCTpABn0ko4JVwQNh5+2H7VAN/iuvdWp1oA21Mk4ZcBjbis2SDMgwzewJYrJELUJ5mvJTLIA0zLL0HnklYyIhzz/5wndJm8F8x5k/epxOyOhKMfONb/GCnJP3BoghlO9hh/7K2fhIky6zrTXW1fBXcwtkBIdBgp8RVp4bNcRrPOoSx6k11uoyZ7g/
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: external-dns-credentials
      namespace: external-dns

