apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - git@github.com/kube-champ/josa-demo/infrastructure/base/external-dns
  - external-dns-credentials.yaml
patchesStrategicMerge:
  - patch-release.yaml