apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack
spec:
  type: slack
  channel: josa-alerts
  # webhook address (ignored if secretRef is specified)
  # address: https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK
  secretRef:
    name: flux-slack-url
  # HTTP(S) proxy (optional)
  # proxy: https://proxy.corp:8080
  # secret containing the webhook address (optional)
  # secretRef:
  #   name: webhook-url