apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: certs
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infrastructure/josa/certs
  prune: true
  validation: clients