apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: service-monitors
  namespace: monitoring
spec:
  interval: 1m0s
  dependsOn:
    - name: infrastructure
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infrastructure/josa/service-monitors
  prune: true
  validation: clients